/**
 * Phase 8.2 — one-off setup script: creates the `dispute-evidence` Supabase
 * Storage bucket, if it doesn't already exist.
 *
 * Unlike `avatars`/`product-images`, this bucket is PRIVATE — dispute
 * evidence (photos of damaged/wrong items, etc.) is sensitive and must never
 * be reachable via a public URL. Reads only ever happen through short-lived
 * signed URLs generated by the backend after verifying the caller is a
 * participant (buyer/seller on that dispute) or an admin.
 *
 * Safe to re-run: no-ops if the bucket already exists.
 * Usage: node scripts/setupDisputeEvidenceBucket.js
 *
 * Live/remote bucket creation requires explicit user approval — do not run
 * this against the production Supabase project ref until that approval is
 * given. Safe to run against a disposable local Supabase instance for
 * validation.
 */
require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required in backend/.env');
  process.exit(1);
}
const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

const BUCKET = 'dispute-evidence';

async function run() {
  const { data: buckets, error: listErr } = await sb.storage.listBuckets();
  if (listErr) throw new Error('listBuckets: ' + listErr.message);

  const exists = (buckets || []).some((b) => b.name === BUCKET);
  if (exists) {
    console.log(`Bucket "${BUCKET}" already exists. No changes made.`);
  } else {
    const { error: createErr } = await sb.storage.createBucket(BUCKET, {
      public: false,
      fileSizeLimit: 5 * 1024 * 1024, // 5 MB
      allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    });
    if (createErr) throw new Error('createBucket: ' + createErr.message);
    console.log(`Created bucket "${BUCKET}" (private, 5MB/file limit, jpeg/png/webp only).`);
  }

  console.log('\nWrite access: only the backend service-role key ever writes to this bucket.');
  console.log('Reads: only via short-lived signed URLs issued to verified dispute participants/admins.');
  console.log('No public read policy exists — objects are unreachable without a signed URL.');
}

run().catch((err) => { console.error('SETUP FAILED:', err.message); process.exit(1); });
